services:
  app:
    build: .
    ports:
      - "7777:7777"
    environment:
      PORT: 7777
      MONGO_URI: mongodb://db:27017/task-tracker
      REDIS_URL: redis://redis:6379
      JWT_SECRET: mysecretkey0409
    depends_on:
      - db
      - redis

  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
